services:
  - type: web
    name: kiddie-color-creations-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt && cd backend && python -c 'from app import app; from flask_migrate import init, migrate, upgrade; from flask import current_app; import os; app.app_context().push(); init() if not os.path.exists(\"migrations\") else None; migrate(message=\"Initial migration\"); upgrade()'"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ADMIN_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true # Will be used for first-time setup only
      - key: IMAGE_API_ENDPOINT
        value: https://api.gptgod.online/v1/chat/completions
      - key: IMAGE_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: kiddie-color-creations-db
          property: connectionString
    databases:
      - name: kiddie-color-creations-db
        plan: free
